import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';

vi.mock('@/lib/roles', () => ({
  CAMPAIGN_ROLES: ['super_admin', 'agency_owner', 'admin', 'gerente', 'agente'],
  requireRole: vi.fn(),
  isRoleContext: vi.fn(),
}));
vi.mock('@/lib/llm-providers', () => ({ resolveApiKey: vi.fn() }));
vi.mock('@/agents/vision-analyzer', () => ({ analyzeAssets: vi.fn() }));

import { analyzeAssets } from '@/agents/vision-analyzer';
import { GET } from './route';
import { resolveApiKey } from '@/lib/llm-providers';
import { isRoleContext, requireRole } from '@/lib/roles';

const originalAllowedRoots = process.env.INVENTORY_ALLOWED_ROOTS;
let temporaryDirectory: string;
let baseRoot: string;
let workspaceRoot: string;

function request(requestedPath?: string): NextRequest {
  const url = new URL('http://localhost/api/inventory');
  if (requestedPath) url.searchParams.set('path', requestedPath);
  return new NextRequest(url);
}

function createDirectory(directory: string): void {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- Test paths are descendants of an isolated directory generated by Node.
  fs.mkdirSync(directory, { recursive: true });
}

describe('GET /api/inventory', () => {
  beforeEach(() => {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- os.tmpdir() is trusted and the random suffix is generated by Node.
    temporaryDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'inventory-route-'));
    baseRoot = path.join(temporaryDirectory, 'inventory');
    workspaceRoot = path.join(baseRoot, 'workspace-a');
    createDirectory(workspaceRoot);
    process.env.INVENTORY_ALLOWED_ROOTS = baseRoot;

    vi.mocked(requireRole).mockResolvedValue({
      auth: { userId: 'user-1', email: 'user@rai.local' },
      workspace: { id: 'workspace-a', ownerId: 'owner-1', name: 'Workspace A' },
      role: 'admin',
    });
    vi.mocked(isRoleContext).mockReturnValue(true);
    vi.mocked(resolveApiKey).mockResolvedValue(null);
    vi.mocked(analyzeAssets).mockReset();
  });

  afterEach(() => {
    if (originalAllowedRoots === undefined) delete process.env.INVENTORY_ALLOWED_ROOTS;
    else process.env.INVENTORY_ALLOWED_ROOTS = originalAllowedRoots;
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Only the isolated temporary directory created in beforeEach is removed.
    fs.rmSync(temporaryDirectory, { recursive: true, force: true });
    vi.clearAllMocks();
  });

  it('devuelve 400 si falta path', async () => {
    const response = await GET(request());

    expect(response.status).toBe(400);
  });

  it('devuelve 403 sin revelar rutas al pedir el inventario de otro workspace', async () => {
    const workspaceBRoot = path.join(baseRoot, 'workspace-b');
    createDirectory(workspaceBRoot);

    const response = await GET(request(workspaceBRoot));
    const body = await response.json();

    expect(response.status).toBe(403);
    expect(JSON.stringify(body)).not.toContain(temporaryDirectory);
  });

  it('devuelve 404 sin revelar rutas para un descendiente inexistente', async () => {
    const missingPath = path.join(workspaceRoot, 'missing');

    const response = await GET(request(missingPath));
    const body = await response.json();

    expect(response.status).toBe(404);
    expect(JSON.stringify(body)).not.toContain(temporaryDirectory);
  });

  it('enumera únicamente descendientes validados del workspace autenticado', async () => {
    const dayRoot = path.join(workspaceRoot, 'Día 1');
    const imagePath = path.join(dayRoot, 'asset.jpg');
    createDirectory(dayRoot);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- File is created inside this test's isolated workspace directory.
    fs.writeFileSync(imagePath, 'image');

    const response = await GET(request(workspaceRoot));
    const body = await response.json();
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Expected path is inside this test's isolated workspace directory.
    const realDayRoot = fs.realpathSync(dayRoot);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Expected path is inside this test's isolated workspace directory.
    const realImagePath = fs.realpathSync(imagePath);

    expect(response.status).toBe(200);
    expect(body.days).toHaveLength(1);
    expect(body.days[0]).toMatchObject({
      dayNumber: 1,
      folderPath: realDayRoot,
      existingAssets: [{ name: 'asset.jpg', path: realImagePath, sizeBytes: 5 }],
      hasContent: true,
    });
    expect(analyzeAssets).not.toHaveBeenCalled();
  });
});
