import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  getInventoryAllowedRoots,
  InventoryPathError,
  isPathWithinRoot,
  resolveInventoryDescendant,
  resolveInventoryRoot,
  validateInventoryWorkspaceId,
} from '@/lib/inventory-paths';

const temporaryDirectories: string[] = [];

function createTemporaryDirectory(): string {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- os.tmpdir() is trusted and the random suffix is generated by Node.
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'inventory-paths-'));
  temporaryDirectories.push(directory);
  return directory;
}

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Only test directories created by createTemporaryDirectory are removed.
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

describe('inventory-paths', () => {
  it('usa <cwd>/inventory/<workspaceId> cuando no hay configuración', () => {
    const cwd = path.resolve('test-workspace');
    expect(getInventoryAllowedRoots('workspace-a', undefined, cwd)).toEqual([
      path.join(cwd, 'inventory', 'workspace-a'),
    ]);
  });

  it('deriva el mismo workspace bajo múltiples bases configuradas', () => {
    const cwd = path.resolve('test-workspace');
    const configured = ['assets', 'uploads'].join(path.delimiter);

    expect(getInventoryAllowedRoots('workspace-a', configured, cwd)).toEqual([
      path.join(cwd, 'assets', 'workspace-a'),
      path.join(cwd, 'uploads', 'workspace-a'),
    ]);
  });

  it.each(['', '.', '..', '../workspace-b', 'workspace/b', 'workspace\\b', 'workspace.b']) (
    'rechaza workspaceId inválido: %s',
    (workspaceId) => {
      expect(() => validateInventoryWorkspaceId(workspaceId)).toThrowError(
        expect.objectContaining<Partial<InventoryPathError>>({ code: 'NOT_ALLOWED' })
      );
    }
  );

  it('acepta la raíz exacta y descendientes, pero bloquea traversal y prefix bypass', () => {
    const root = path.resolve('inventory');

    expect(isPathWithinRoot(root, root)).toBe(true);
    expect(isPathWithinRoot(path.join(root, 'client', 'Día 1'), root)).toBe(true);
    expect(isPathWithinRoot(path.resolve(root, '..', 'inventory-secret'), root)).toBe(false);
    expect(isPathWithinRoot(path.resolve(root, '..', 'outside'), root)).toBe(false);
  });

  it('aísla workspace A de workspace B', () => {
    const temporaryDirectory = createTemporaryDirectory();
    const workspaceARoot = path.join(temporaryDirectory, 'inventory', 'workspace-a');
    const workspaceBRoot = path.join(temporaryDirectory, 'inventory', 'workspace-b');
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Path is contained in this test's freshly created temporary directory.
    fs.mkdirSync(workspaceARoot, { recursive: true });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Path is contained in this test's freshly created temporary directory.
    fs.mkdirSync(workspaceBRoot, { recursive: true });

    const workspaceARoots = getInventoryAllowedRoots(
      'workspace-a',
      path.join(temporaryDirectory, 'inventory')
    );

    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Comparison uses the same trusted temporary test path created immediately above.
    expect(resolveInventoryRoot(workspaceARoot, workspaceARoots)).toBe(fs.realpathSync(workspaceARoot));
    expect(() => resolveInventoryRoot(workspaceBRoot, workspaceARoots)).toThrowError(
      expect.objectContaining<Partial<InventoryPathError>>({ code: 'NOT_ALLOWED' })
    );
  });

  it('bloquea un symlink descendiente que escapa de la raíz efectiva', () => {
    const temporaryDirectory = createTemporaryDirectory();
    const baseRoot = path.join(temporaryDirectory, 'inventory');
    const allowedRoot = path.join(baseRoot, 'workspace-a');
    const outsideRoot = path.join(temporaryDirectory, 'outside');
    const linkedRoot = path.join(allowedRoot, 'Día 1');
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Path is contained in this test's freshly created temporary directory.
    fs.mkdirSync(allowedRoot, { recursive: true });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Path is contained in this test's freshly created temporary directory.
    fs.mkdirSync(outsideRoot);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Both paths are contained in the isolated temporary directory and specifically exercise symlink escape handling.
    fs.symlinkSync(outsideRoot, linkedRoot, process.platform === 'win32' ? 'junction' : 'dir');

    const allowedRoots = getInventoryAllowedRoots('workspace-a', baseRoot);
    expect(() => resolveInventoryDescendant(allowedRoot, 'Día 1', allowedRoots)).toThrowError(
      expect.objectContaining<Partial<InventoryPathError>>({ code: 'NOT_ALLOWED' })
    );
  });
});
